# Generated by Django 5.2.7 on 2025-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_follow_notification_postview_alter_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
