# Generated by Django 5.2.7 on 2025-10-13 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique single-word identifier (no spaces).', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', 'Name must be a single word (letters, numbers, _ or -'), django.core.validators.MinLengthValidator(4, 'Name must be at least 4 character long')])),
                ('description', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='communities/profiles/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='communities/covers/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members_count', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-members_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name'], name='community_c_name_d6f8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['visibility'], name='community_c_visibil_8343a4_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['members_count'], name='community_c_members_c153f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('user', 'community')},
        ),
    ]
