# Generated by Django 5.2.7 on 2025-10-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestsubcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='InterestCategory',
        ),
        migrations.DeleteModel(
            name='InterestSubCategory',
        ),
    ]
